num = [10,20,30,40,50,60,70]
print("Original List", num)
print()
n = len(num)
print("Number Of Element in List:", n)
print()
num.append(80)
print("After Inserting 80 ", num)
print()
num1 = num.copy()
print("Newly Created Copied List Num1:", num1)
print()
num.append(50)
print(num)
print()
n = num.count(50)
print("Nomber of Times 50 Found in The List is :", n)
print()
num.remove(70)
print("After Removing 70", num)
print()
num.pop()
print("List After Using pop()", num)
print()
num.sort()
print("List After Sorting", num)
print()
num.reverse()
print("List After After Reversing", num)
print()
num.clear()
print("List After Clearing all Elements", num)
 
