from array import*
arr=array('i',[10,20,30,40,50])
print('original array:',arr)
arr.append(30)
arr.append(60)
print("Array After Appending 30 And 60 :",arr)
arr.insert(1,99)
print("Array After Inserting 99 at Posistion 1 :",arr)
arr.remove(20)
print("Array After Removing 20 :",arr)
n=arr.pop()
print("Array After Using POP() :",arr)
print("POPED Element",n)
n=arr.index(30)
print("First Occurence of 30 is at Position",n)
lst=arr.tolist()
print("List:",lst)
print("Array:",arr)
